{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 1,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "\n",
      "\n",
      "Package plan for installation in environment C:\\ProgramData\\Miniconda3:\n",
      "\n",
      "The following NEW packages will be INSTALLED:\n",
      "\n",
      "    beautifulsoup4:  4.6.0-py36hd4cc5e8_1 \n",
      "    cycler:          0.10.0-py36h009560c_0\n",
      "    freetype:        2.8-h51f8f2c_1       \n",
      "    icc_rt:          2017.0.4-h97af966_0  \n",
      "    icu:             58.2-ha66f8fd_1      \n",
      "    intel-openmp:    2018.0.0-8           \n",
      "    jpeg:            9b-hb83a4c4_2        \n",
      "    kiwisolver:      1.0.1-py36h12c3424_0 \n",
      "    libpng:          1.6.34-h79bbb47_0    \n",
      "    matplotlib:      2.2.2-py36h153e9ff_1 \n",
      "    mkl:             2018.0.2-1           \n",
      "    mkl_fft:         1.0.1-py36h452e1ab_0 \n",
      "    mkl_random:      1.0.1-py36h9258bd6_0 \n",
      "    numpy:           1.14.2-py36h5c71026_1\n",
      "    pandas:          0.22.0-py36h6538335_0\n",
      "    pyparsing:       2.2.0-py36h785a196_1 \n",
      "    pyqt:            5.9.2-py36h1aa27d4_0 \n",
      "    python-dateutil: 2.7.2-py36_0         \n",
      "    pytz:            2018.4-py36_0        \n",
      "    qt:              5.9.5-vc14he4a7d60_0 \n",
      "    sip:             4.19.8-py36h6538335_0\n",
      "    sqlite:          3.23.1-h35aae40_0    \n",
      "    tornado:         5.0.2-py36_0         \n",
      "    zlib:            1.2.11-h8395fce_2    \n",
      "\n",
      "The following packages will be UPDATED:\n",
      "\n",
      "    conda:           4.3.31-py36_0         --> 4.5.2-py36_0     \n",
      "    openssl:         1.0.2n-h74b6da3_0     --> 1.0.2o-h8ea7d77_0\n",
      "\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "\n",
      "CondaIOError: Missing write permissions in: C:\\ProgramData\\Miniconda3\n",
      "#\n",
      "# You don't appear to have the necessary permissions to install packages\n",
      "# into the install area 'C:\\ProgramData\\Miniconda3'.\n",
      "# However you can clone this environment into your home directory and\n",
      "# then make changes to it.\n",
      "# This may be done using the command:\n",
      "#\n",
      "# $ conda create -n my_root --clone=\"C:\\ProgramData\\Miniconda3\"\n",
      "\n",
      "\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Requirement already satisfied: requests in c:\\programdata\\miniconda3\\lib\\site-packages (2.18.4)\n",
      "Requirement already satisfied: html5 in c:\\programdata\\miniconda3\\lib\\site-packages (0.0.9)\n",
      "Requirement already satisfied: lxml in c:\\programdata\\miniconda3\\lib\\site-packages (4.2.1)\n",
      "Requirement already satisfied: chardet<3.1.0,>=3.0.2 in c:\\programdata\\miniconda3\\lib\\site-packages (from requests) (3.0.4)\n",
      "Requirement already satisfied: idna<2.7,>=2.5 in c:\\programdata\\miniconda3\\lib\\site-packages (from requests) (2.6)\n",
      "Requirement already satisfied: urllib3<1.23,>=1.21.1 in c:\\programdata\\miniconda3\\lib\\site-packages (from requests) (1.22)\n",
      "Requirement already satisfied: certifi>=2017.4.17 in c:\\programdata\\miniconda3\\lib\\site-packages (from requests) (2017.11.5)\n",
      "Requirement already satisfied: setuptools>=18.5 in c:\\programdata\\miniconda3\\lib\\site-packages (from html5) (36.5.0.post20170921)\n",
      "Requirement already satisfied: six in c:\\programdata\\miniconda3\\lib\\site-packages (from html5) (1.11.0)\n",
      "Requirement already satisfied: webencodings in c:\\programdata\\miniconda3\\lib\\site-packages (from html5) (0.5.1)\n",
      "Requirement already satisfied: plotly in c:\\programdata\\miniconda3\\lib\\site-packages (2.2.3)\n",
      "Requirement already satisfied: cufflinks in c:\\programdata\\miniconda3\\lib\\site-packages (0.12.1)\n",
      "Requirement already satisfied: folium in c:\\programdata\\miniconda3\\lib\\site-packages (0.5.0)\n",
      "Requirement already satisfied: pytz in c:\\programdata\\miniconda3\\lib\\site-packages (from plotly) (2017.3)\n",
      "Requirement already satisfied: six in c:\\programdata\\miniconda3\\lib\\site-packages (from plotly) (1.11.0)\n",
      "Requirement already satisfied: requests in c:\\programdata\\miniconda3\\lib\\site-packages (from plotly) (2.18.4)\n",
      "Requirement already satisfied: decorator>=4.0.6 in c:\\programdata\\miniconda3\\lib\\site-packages (from plotly) (4.2.1)\n",
      "Requirement already satisfied: nbformat>=4.2 in c:\\programdata\\miniconda3\\lib\\site-packages (from plotly) (4.4.0)\n",
      "Requirement already satisfied: colorlover>=0.2 in c:\\programdata\\miniconda3\\lib\\site-packages (from cufflinks) (0.2.1)\n",
      "Requirement already satisfied: pandas in c:\\programdata\\miniconda3\\lib\\site-packages (from cufflinks) (0.22.0)\n",
      "Requirement already satisfied: branca in c:\\programdata\\miniconda3\\lib\\site-packages (from folium) (0.2.0)\n",
      "Requirement already satisfied: jinja2 in c:\\programdata\\miniconda3\\lib\\site-packages (from folium) (2.10)\n",
      "Requirement already satisfied: chardet<3.1.0,>=3.0.2 in c:\\programdata\\miniconda3\\lib\\site-packages (from requests->plotly) (3.0.4)\n",
      "Requirement already satisfied: idna<2.7,>=2.5 in c:\\programdata\\miniconda3\\lib\\site-packages (from requests->plotly) (2.6)\n",
      "Requirement already satisfied: urllib3<1.23,>=1.21.1 in c:\\programdata\\miniconda3\\lib\\site-packages (from requests->plotly) (1.22)\n",
      "Requirement already satisfied: certifi>=2017.4.17 in c:\\programdata\\miniconda3\\lib\\site-packages (from requests->plotly) (2017.11.5)\n",
      "Requirement already satisfied: jupyter-core in c:\\programdata\\miniconda3\\lib\\site-packages (from nbformat>=4.2->plotly) (4.4.0)\n",
      "Requirement already satisfied: ipython-genutils in c:\\programdata\\miniconda3\\lib\\site-packages (from nbformat>=4.2->plotly) (0.2.0)\n",
      "Requirement already satisfied: jsonschema!=2.5.0,>=2.4 in c:\\programdata\\miniconda3\\lib\\site-packages (from nbformat>=4.2->plotly) (2.6.0)\n",
      "Requirement already satisfied: traitlets>=4.1 in c:\\programdata\\miniconda3\\lib\\site-packages (from nbformat>=4.2->plotly) (4.3.2)\n",
      "Requirement already satisfied: numpy>=1.9.0 in c:\\programdata\\miniconda3\\lib\\site-packages (from pandas->cufflinks) (1.14.0)\n",
      "Requirement already satisfied: python-dateutil>=2 in c:\\programdata\\miniconda3\\lib\\site-packages (from pandas->cufflinks) (2.6.1)\n",
      "Requirement already satisfied: MarkupSafe>=0.23 in c:\\programdata\\miniconda3\\lib\\site-packages (from jinja2->folium) (1.0)\n"
     ]
    }
   ],
   "source": [
    "\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 2,
   "metadata": {},
   "outputs": [
    {
     "ename": "SyntaxError",
     "evalue": "invalid syntax (<ipython-input-2-0a8cf7b99133>, line 1)",
     "output_type": "error",
     "traceback": [
      "\u001b[1;36m  File \u001b[1;32m\"<ipython-input-2-0a8cf7b99133>\"\u001b[1;36m, line \u001b[1;32m1\u001b[0m\n\u001b[1;33m    python -m pip install --upgrade pip\u001b[0m\n\u001b[1;37m                ^\u001b[0m\n\u001b[1;31mSyntaxError\u001b[0m\u001b[1;31m:\u001b[0m invalid syntax\n"
     ]
    }
   ],
   "source": []
  },
  {
   "cell_type": "code",
   "execution_count": 16,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "enter any location you want to travel to: london canada\n",
      "{'lat': 42.9849233, 'lng': -81.2452768}\n"
     ]
    },
    {
     "data": {
      "text/plain": [
       "dict"
      ]
     },
     "execution_count": 16,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "#import requests\n",
    "#import json\n",
    "#\n",
    "#city = input(\"enter a city EX:Paris \")\n",
    "#country = input(\"enter the country for the City EX: France \")\n",
    "\n",
    "#print ('your location is',  city,',', country, \"is this correct?\")\n",
    "\n",
    "\n",
    "import json\n",
    "import pandas as pd\n",
    "import requests\n",
    "import warnings\n",
    "warnings.filterwarnings('ignore')\n",
    "\n",
    "user_location = input('enter any location you want to travel to: ')\n",
    "\n",
    "\n",
    "url = 'https://maps.googleapis.com/maps/api/geocode/json'\n",
    "options = {'address' : user_location ,'key' : 'AIzaSyBf6JMjuorNaxHvlkS4Es4TOaABbDAkh5s'}\n",
    "requestpost = requests.get(url , params = options)\n",
    "response_data = requestpost.json()\n",
    "#print(response_data ['results'][0]['geometry']['location'])\n",
    "location = response_data ['results'][0]['geometry']['location']\n",
    "print(location)\n",
    "type(location)\n",
    "#print(response_data ['results'][0]['long_name'])\n",
    "#coords = response_data ['results'][0]['geometry']['location'])\n",
    "\n",
    "\n",
    "\n",
    "\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 15,
   "metadata": {},
   "outputs": [
    {
     "ename": "NameError",
     "evalue": "name 'latitude' is not defined",
     "output_type": "error",
     "traceback": [
      "\u001b[1;31m---------------------------------------------------------------------------\u001b[0m",
      "\u001b[1;31mNameError\u001b[0m                                 Traceback (most recent call last)",
      "\u001b[1;32m<ipython-input-15-ad07db7b74ee>\u001b[0m in \u001b[0;36m<module>\u001b[1;34m()\u001b[0m\n\u001b[0;32m      1\u001b[0m \u001b[0murl\u001b[0m \u001b[1;33m=\u001b[0m \u001b[1;34m'https://api.darksky.net/forecast/aacb0f0b61f75df0a549ae33decf04e6/'\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n\u001b[1;32m----> 2\u001b[1;33m \u001b[0moptions\u001b[0m \u001b[1;33m=\u001b[0m \u001b[1;33m{\u001b[0m \u001b[0mlatitude\u001b[0m \u001b[1;33m:\u001b[0m \u001b[1;34m'lat'\u001b[0m \u001b[1;33m,\u001b[0m \u001b[0mLongitude\u001b[0m \u001b[1;33m:\u001b[0m \u001b[1;34m'lng'\u001b[0m\u001b[1;33m}\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n\u001b[0m\u001b[0;32m      3\u001b[0m \u001b[0mresponse\u001b[0m \u001b[1;33m=\u001b[0m \u001b[0mrequests\u001b[0m\u001b[1;33m.\u001b[0m\u001b[0mget\u001b[0m\u001b[1;33m(\u001b[0m\u001b[0murl\u001b[0m\u001b[1;33m)\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n\u001b[0;32m      4\u001b[0m \u001b[1;31m#options = {key : cdbe8c74b175791b3feb582f1234f5a1}\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n\u001b[0;32m      5\u001b[0m \u001b[0mprint\u001b[0m\u001b[1;33m(\u001b[0m\u001b[0mlat\u001b[0m\u001b[1;33m,\u001b[0m \u001b[0mlng\u001b[0m\u001b[1;33m)\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n",
      "\u001b[1;31mNameError\u001b[0m: name 'latitude' is not defined"
     ]
    }
   ],
   "source": [
    "url = 'https://api.darksky.net/forecast/aacb0f0b61f75df0a549ae33decf04e6/'\n",
    "options = { latitude : 'lat' , Longitude : 'lng'}\n",
    "response = requests.get(url)\n",
    "#options = {key : cdbe8c74b175791b3feb582f1234f5a1}\n",
    "print(lat, lng)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 5,
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/plain": [
       "False"
      ]
     },
     "execution_count": 5,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "response.ok\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 6,
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/plain": [
       "'{\"code\":400,\"error\":\"The given location (or time) is invalid.\"}'"
      ]
     },
     "execution_count": 6,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "response.text"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 7,
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/plain": [
       "{'code': 400, 'error': 'The given location (or time) is invalid.'}"
      ]
     },
     "execution_count": 7,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "geodata = response.json()  # try to decode the response from JSON format\n",
    "geodata                    # this is now a Python object variable"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 8,
   "metadata": {},
   "outputs": [
    {
     "ename": "KeyError",
     "evalue": "'results'",
     "output_type": "error",
     "traceback": [
      "\u001b[1;31m---------------------------------------------------------------------------\u001b[0m",
      "\u001b[1;31mKeyError\u001b[0m                                  Traceback (most recent call last)",
      "\u001b[1;32m<ipython-input-8-2af5c2fe4640>\u001b[0m in \u001b[0;36m<module>\u001b[1;34m()\u001b[0m\n\u001b[1;32m----> 1\u001b[1;33m \u001b[0mcoords\u001b[0m \u001b[1;33m=\u001b[0m \u001b[0mgeodata\u001b[0m \u001b[1;33m[\u001b[0m\u001b[1;34m'results'\u001b[0m\u001b[1;33m]\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n\u001b[0m\u001b[0;32m      2\u001b[0m \u001b[0mcoords\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n",
      "\u001b[1;31mKeyError\u001b[0m: 'results'"
     ]
    }
   ],
   "source": [
    "coords = geodata ['results']\n",
    "coords"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.6.3"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 2
}
